url: https://dgladyshev.github.io
baseurl: 

# Site settings
title: CraftCraft
email: m.gladysheva@craftcraft.shop
#todo
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Дмитрий Гладышев
  pic: 1
  position: Разработка 
  social:
    - title: facebook
      url: https://www.facebook.com/dagladyshev
    - title: linkedin
      url: https://www.linkedin.com/in/dgladyshev

- name: Марина Гладышева
  pic: 2
  position: Исследования/UX
  social:
    - title: facebook
      url: https://www.facebook.com/marina.gladysheve.issadovskaya
    - title: linkedin
      url: https://www.linkedin.com/in/marina-gladysheva

- name: Александр Иссадовский
  pic: 2
  position: Финансы
  social:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/_craftcraftshop_
  - title: facebook
    url: https://www.facebook.com/groups/366424640387789
  - title: vkontakte
    url: https://vk.com/public138009190


# Postal address (add as many lines as necessary)
address:
  - line: x
  - line: x

# Build settings
markdown: kramdown
permalink: pretty